name: Build LaTeX PDF and Deploy Jekyll

on:
  push:
    branches:
      - main
      - actions

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TEX_ROOT: tex-source
      JEKYLL_ROOT: docs
      PDF_OUTPUT_NAME: aluffi-solutions-book.pdf

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache additional TeX packages
        uses: actions/cache@v3
        with:
          path: ~/.TinyTeX
          key: texlive-${{ runner.os }}-v1

      - name: Set up TinyTeX with required packages
        uses: r-lib/actions/setup-tinytex@v2
        with:
          cache: true
          tlmgr-packages: |
            collection-fontsrecommended
            collection-latexrecommended
            amsmath
            amssymb
            amsthm
            # mathtools
            latexmk
          cache-version: 1

             - name: Ensure extra LaTeX packages are installed
        run: |
          tlmgr install mathtools bm

      - name: Compile LaTeX document with latexmk
        working-directory: ${{ env.TEX_ROOT }}
        run: |
          mkdir -p ../generated-pdfs
          latexmk -pdf -interaction=nonstopmode -outdir=build main.tex
          mv build/main.pdf ../generated-pdfs/${{ env.PDF_OUTPUT_NAME }}
          latexmk -c -outdir=build main.tex

      - name: Copy generated PDF to Jekyll assets
        run: |
          mkdir -p ${{ env.JEKYLL_ROOT }}/assets/solutions
          cp generated-pdfs/${{ env.PDF_OUTPUT_NAME }} ${{ env.JEKYLL_ROOT }}/assets/solutions/

      - name: Setup Ruby for Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install Jekyll dependencies
        working-directory: ${{ env.JEKYLL_ROOT }}
        run: |
          bundle install

      - name: Build Jekyll site
        working-directory: ${{ env.JEKYLL_ROOT }}
        run: |
          bundle exec jekyll build

      - name: Deploy Jekyll site to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.JEKYLL_ROOT }}/_site
