# .github/workflows/build-latex.yml (Revised for Caching and Package Installation)

name: Build LaTeX Solutions and Publish

on:
  push:
    branches:
      - main
      - test

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      TEX_ROOT: tex-source # Adjust this to your main solutions directory
      JEKYLL_ROOT: docs     # The folder where your Jekyll site lives

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # === MODIFIED TINYTEX SETUP WITH EXPLICIT PACKAGE CACHING ===
    - name: Set up TinyTeX and Cache Key Packages
      uses: r-lib/actions/setup-tinytex@v2
      with:
        # 'cache: true' is the default for v2.
        cache: true
        # Add your largest/most stable packages/collections here.
        # Explicitly adding core packages like amsmath, amssymb, amsthm, mathtools
        # alongside collections ensures they are prioritized for caching by setup-tinytex.
        tlmgr-packages: |
          collection-fontsrecommended
          collection-latexrecommended
          amsmath
          amssymb
          amsthm
          mathtools 
          latexmk
          # Add any other frequently used, large, or foundational packages/collections
          # e.g., scheme-full (if you need a very comprehensive setup)
          # graphicx # (usually part of latex-recommended or base)
        # Increment 'cache-version' if you make significant changes to 'tlmgr-packages'
        # or if you suspect the cache is stale and want to force a refresh.
        cache-version: 2 # Incremented due to changes in tlmgr-packages
    # === END MODIFIED TINYTEX SETUP ===

    - name: Install Additional LaTeX Packages from File
      # This step installs any remaining packages listed in latex_packages.txt
      # that might not have been covered by the setup-tinytex step.
      # tlmgr will skip packages already installed.
      run: |
        echo "Ensuring all LaTeX packages from ${{ env.TEX_ROOT }}/latex_packages.txt are present..."
        PACKAGE_FILE="${{ env.TEX_ROOT }}/latex_packages.txt"
        
        if [ -f "$PACKAGE_FILE" ] && [ -s "$PACKAGE_FILE" ]; then
          echo "Packages to install/verify from $PACKAGE_FILE:"
          # Print non-empty, non-comment lines from the package file
          grep -vE '^\s*#|^\s*$' "$PACKAGE_FILE" || echo "No non-comment packages in file to list."

          # Read non-empty, non-comment lines, and pass to tlmgr install
          # Removed redundant '-n 1' as '-I {}' implies processing one line at a time.
          # The '|| true' allows the workflow to continue if a package fails, is a meta-package, or is already installed.
          grep -vE '^\s*#|^\s*$' "$PACKAGE_FILE" | xargs -r -I {} sh -c 'echo "Attempting to install/verify from file: {}"; tlmgr install "{}" || echo "Notice: Could not install {} from file, or it was already present/a meta-package, or it is part of a collection already installed."'
        else
          echo "No packages listed in $PACKAGE_FILE, or file is empty/not found. Skipping this step."
        fi
        echo "Additional LaTeX package installation process from file complete."

    - name: Create directory for generated PDFs
      run: mkdir -p ${{ github.workspace }}/generated-pdfs

    - name: Compile Main LaTeX Document to PDF
      working-directory: ${{ env.TEX_ROOT }}
      run: |
        MAIN_TEX_FILE="main.tex"
        TEMP_LATEX_OUTPUT_DIR="latex_build_temp"
        mkdir -p "$TEMP_LATEX_OUTPUT_DIR"

        FINAL_PDF_OUTPUT_DIR="${{ github.workspace }}/generated-pdfs"
        OUTPUT_PDF_NAME="aluffi-solutions-book.pdf"

        echo "Compiling $MAIN_TEX_FILE from ${{ env.TEX_ROOT }} and outputting to $FINAL_PDF_OUTPUT_DIR/$OUTPUT_PDF_NAME..."
        
        # Compile using latexmk
        # Added -interaction=nonstopmode to prevent hangs on errors for CI
        latexmk -pdf -interaction=nonstopmode -outdir="$TEMP_LATEX_OUTPUT_DIR" "$MAIN_TEX_FILE"

        mkdir -p "$FINAL_PDF_OUTPUT_DIR"
        # Check if PDF was created before moving
        if [ -f "$TEMP_LATEX_OUTPUT_DIR/main.pdf" ]; then
          mv "$TEMP_LATEX_OUTPUT_DIR/main.pdf" "$FINAL_PDF_OUTPUT_DIR/$OUTPUT_PDF_NAME"
          echo "PDF successfully compiled and moved."
        else
          echo "Error: PDF compilation failed. No PDF file found at $TEMP_LATEX_OUTPUT_DIR/main.pdf."
          # Optionally, print the log file content for easier debugging in GitHub Actions
          if [ -f "$TEMP_LATEX_OUTPUT_DIR/main.log" ]; then
            echo "Displaying contents of $TEMP_LATEX_OUTPUT_DIR/main.log:"
            cat "$TEMP_LATEX_OUTPUT_DIR/main.log"
          fi
          exit 1 # Fail the step if PDF is not created
        fi

        # Clean up auxiliary files
        latexmk -c -outdir="$TEMP_LATEX_OUTPUT_DIR" "$MAIN_TEX_FILE"
        rm -rf "$TEMP_LATEX_OUTPUT_DIR"

    - name: Copy generated PDFs into Jekyll site assets
      run: |
        JEKYLL_ASSETS_DIR="${{ github.workspace }}/${{ env.JEKYLL_ROOT }}/assets/solutions/"
        mkdir -p "$JEKYLL_ASSETS_DIR"
        # Ensure the PDF exists before copying
        PDF_TO_COPY="${{ github.workspace }}/generated-pdfs/aluffi-solutions-book.pdf"
        if [ -f "$PDF_TO_COPY" ]; then
          cp "$PDF_TO_COPY" "$JEKYLL_ASSETS_DIR"
          echo "PDF copied to Jekyll assets."
        else
          echo "Error: Compiled PDF not found at $PDF_TO_COPY. Cannot copy to Jekyll assets."
          exit 1 # Fail the step if PDF is not found
        fi

    - name: Setup Ruby for Jekyll
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1' # Specify a Ruby version compatible with your Jekyll setup
        bundler-cache: true 
        cache-version: 1    # Increment if Gemfile.lock changes

    - name: List contents of Jekyll directory
      run: ls -lR
      working-directory: ${{ env.JEKYLL_ROOT }}

    - name: Install Ruby Gems
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
      working-directory: ${{ env.JEKYLL_ROOT }}

    - name: Diagnose Ruby/Jekyll Setup (Optional)
      run: |
        echo "Current directory: $(pwd)"
        echo "Contents of Gemfile.lock: $(ls Gemfile.lock || echo 'Gemfile.lock not found')"
        echo "Bundler version: $(bundle --version)"
        echo "Jekyll executable location: $(bundle exec which jekyll || echo 'Jekyll executable not found via bundle exec')"
        echo "PATH: $PATH"
      working-directory: ${{ env.JEKYLL_ROOT }}

    - name: Build Jekyll site
      run: |
        echo "Attempting to build Jekyll site..."
        bundle exec jekyll build --trace
      working-directory: ${{ env.JEKYLL_ROOT }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ github.workspace }}/${{ env.JEKYLL_ROOT }}/_site
        # cname: your-custom-domain.com # Optional
